- import_playbook: etherboy-deploy-instances.yaml

- name: Local
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: "wait for Etherboy to come up"
    uri:
      url: "http://{{ groups['launched-int'][0] }}:46658/query"
      status_code: 200
    register: result
    until: result.status == 200
    retries: 60
    delay: 1
  - name: Run loadtest
    command: "docker run -e HOST={{ groups['launched-int'][0] }} -e INFLUXDB_HOST={{ influxdb_host }} --rm docker.io/loomload/loadtest:latest"

- name: Schedule shutdown
  hosts: launched
  become: yes
  gather_facts: yes
  connection: ssh
  tasks:
    - name: shutdown
      command: /sbin/shutdown -h "{{ life_timeout }}"
      sudo: yes