- import_playbook: etherboy-deploy-instances.yaml

- name: Local
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Wait 300 seconds for port 8000 of any IP to close active connections, don't start checking for 10 seconds
    wait_for:
      host: groups['launched-int'][0]
      port: 9999
      delay: 10
  - name: Run loadtest
    command: docker run -e HOST={{ groups['launched-int'][0] }} -e INFLUXDB_HOST={{ influxdb_host }} --rm docker.io/loomload/loadtest

- name: Shutdown etherboy instance
  hosts: launched
  become: yes
  gather_facts: yes
  connection: ssh
  tasks:
    - name: shutdown
      command: /sbin/shutdown -h now
      sudo: yes