---
- name: Local
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Retrieve the etherboycli binary
    command: curl -sL -o /tmp/etherboycli-{{ etherboy_build }} https://private.delegatecall.com/etherboy/linux/{{ etherboy_build }}/etherboycli creates=/tmp/etherboycli-{{ etherboy_build }}

  - name: Retrieve the etherboy out of process plugin
    command: curl -sL -o /tmp/etherboycore.0.0.1-{{ etherboy_build }} https://private.delegatecall.com/etherboy/linux/{{ etherboy_build }}/etherboycore.0.0.1 creates=/tmp/etherboycore.0.0.1-{{ etherboy_build }}

  - name: Retrieve the loom binary
    command: curl -sL -o /tmp/loom-{{ loom_build }} https://private.delegatecall.com/loom/linux/{{ loom_build }}/loom creates=/tmp/loom-{{ loom_build }}

- name: Manage etherboy instances
  hosts: etherboy
  become: yes
  gather_facts: yes
  connection: ssh
  roles:
    - { role: etherboy, tags: ['etherboy'], working_directory: /home/ubuntu }
    - role: node_exporter

- name: Manage monitoring etherboy instances
  hosts: monitoring
  gather_facts: yes
  roles:
    - docker
    - influxdb
    - prometheus
    - grafana
