---
- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    service_account_email: ady-15@robotic-catwalk-188706.iam.gserviceaccount.com
    credentials_file: ~/git/loomnetwork-bb86b8677f84.json
    project_id: robotic-catwalk-188706

  tasks:

  - name: Create SSD volumes for GCE nodes
    local_action:
      module: gce_pd
      size_gb: "{{ hostvars[item]['disk_size'] }}"
      name: "ssdisk-{{ hostvars[item]['ansible_hostname'] }}"
      disk_type: pd-ssd
      delete_on_termination: no
      image: "{{ hostvars[item]['image'] }}"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"
      zone: "{{ hostvars[item]['zone'] }}"
    with_items: "{{ groups['google_compute'] }}"
    when: groups['google_compute'] is defined

  - name: Launch instances on GCE
    local_action:
      module: gce
      name: "{{ hostvars[item]['ansible_hostname'] }}"
      machine_type: "{{ hostvars[item]['machine_type'] }}"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"
      state: present
      network: "{{ resource_prefix }}-vpc"
      subnetwork: "{{ resource_prefix }}-{{ hostvars[item]['region'] }}"
      tags: "{{ resource_prefix }}-targets"
      zone: "{{ hostvars[item]['zone'] }}"
      disks:
        - name: "ssdisk-{{ hostvars[item]['ansible_hostname'] }}"
          mode: READ_WRITE
    register: gce
    with_items: "{{ groups['google_compute'] }}"
    when: groups['google_compute'] is defined

  # - debug:
  #     var: gce.results

  - name: Initialize list to save IP addresses
    set_fact:
      gce_public_ips: []

  - name: Collect GCE IP addresses
    set_fact:
      gce_public_ips: "{{ gce_public_ips }} + [ '{{ item.instance_data[0].public_ip }}/32' ]"
    with_items:
    - "{{ gce.results }}"
    when: groups['google_compute'] is defined

  - name: AWS key pair
    local_action:
      module: ec2_key
      name: "{{ resource_prefix }}_key-{{ item.key }}"
      region: "{{ item.key }}"
    with_dict: "{{ aws_regions }}"
    when: groups['amazon_ec2'] is defined
    register: aws_keypairs

  - name: Save key pairs locally
    local_action:
      module: copy
      content: "{{ item.key.private_key }}"
      dest: "~/.ssh/{{ resource_prefix }}_key-{{ item.item.key }}.pem"
      mode: 0600
    with_items: "{{ aws_keypairs.results }}"
    when: aws_keypairs.changed

  - name: AWS security groups in each region
    local_action:
      module: ec2_group
      name: "{{ resource_prefix }}_sg-{{ item.key }}"
      description: Security group for zombiechain instances
      vpc_id: "{{ item.value.vpc }}"
      region: "{{ item.key }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: icmp
          from_port: 8
          to_port:  -1
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 9100
          to_port: 9100
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          ports:
            - 46656-46658
            - 9999
          cidr_ip:
            - "{{ item.value.vpc_cidr }}"
            - "0.0.0.0/0"
    with_dict: "{{ aws_regions }}"
    when: groups['amazon_ec2'] is defined

  - name: Launch instances on AWS EC2
    local_action:
      module: ec2
      id: "{{ hostvars[item]['ansible_hostname'] }}"
      key_name: "{{ resource_prefix }}_key-{{ hostvars[item]['region'] }}"
      group: "{{ resource_prefix }}_sg-{{ hostvars[item]['region'] }}"
      instance_type: "{{ hostvars[item]['instance_type'] }}"
      image: "{{ aws_regions[hostvars[item]['region']]['ami'] }}"
      wait: yes
      wait_timeout: 500
      instance_profile_name: "{{ resource_prefix }}"
      instance_tags:
          Name: "{{ hostvars[item]['ansible_hostname'] }}"
      region: "{{ hostvars[item]['region'] }}"
      vpc_subnet_id: "{{ hostvars[item]['subnet'] }}"
      assign_public_ip: yes
      monitoring: yes
      user_data: "{{ hostvars[item]['user_data'] }}"
      volumes:
        - device_name: /dev/sda1
          volume_type: io1
          volume_size: "{{ disk_size }}"
          iops: 1000
          delete_on_termination: false
          name: "ssdisk-{{ hostvars[item]['ansible_hostname'] }}"
      state: present
    register: ec2_results
    with_items: "{{ groups['amazon_ec2'] }}"
    when: groups['amazon_ec2'] is defined

  - name: Initialize list to save IP addresses
    set_fact:
      ec2_public_ips: []

  # - debug:
  #     var: ec2_results.results

  - name: Collect AWS IP addresses
    set_fact:
      ec2_public_ips: "{{ ec2_public_ips }} + [ '{{ item.instances[0].public_ip }}/32' ]"
    with_items:
    - "{{ ec2_results.results }}"
    when: groups['amazon_ec2'] is defined

  - name: Append to AWS security groups
    local_action:
      module: ec2_group
      name: "{{ resource_prefix }}_sg-{{ item.key }}"
      description: Security group for zombiechain instances
      vpc_id: "{{ item.value.vpc }}"
      region: "{{ item.key }}"
      purge_rules: no
      rules:
        - proto: tcp
          ports:
            - 46656-46658
            - 9999
          cidr_ip: "{{ gce_public_ips }} + {{ ec2_public_ips }}"
    with_dict: "{{ aws_regions }}"
    when: groups['amazon_ec2'] is defined

  - name: Delete GCE Firewall Rule for peers access
    local_action:
      module: gce_net
      name: "{{ resource_prefix }}-vpc"
      fwname: "{{ resource_prefix }}-blockchain-ports"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"
      state: absent

  - name: Create GCE Firewall Rule for peers access
    local_action:
      module: gce_net
      name: "{{ resource_prefix }}-vpc"
      fwname: "{{ resource_prefix }}-blockchain-ports"
      allowed: tcp:9999;tcp:46656;tcp:46657;tcp:46658
      state: "present"
      src_range: "{{ ec2_public_ips }} + ['0.0.0.0/0']"
      target_tags: "{{ resource_prefix }}-targets"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"
    when: groups['google_compute'] is defined

  - name: Delete GCE Firewall Rule for node_exporter
    local_action:
      module: gce_net
      name: "{{ resource_prefix }}-vpc"
      fwname: "{{ resource_prefix }}-node-exporter"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"
      state: absent

  - name: Create GCE Firewall Rule for node_exporter
    local_action:
      module: gce_net
      name: "{{ resource_prefix }}-vpc"
      fwname: "{{ resource_prefix }}-node-exporter"
      allowed: tcp:9100
      state: "present"
      src_range: "0.0.0.0/0"
      target_tags: "{{ resource_prefix }}-targets"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"
    when: groups['google_compute'] is defined

  - name: Delete GCE Firewall Rule for SSH
    local_action:
      module: gce_net
      name: "{{ resource_prefix }}-vpc"
      fwname: "{{ resource_prefix }}-ssh"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"
      state: absent

  - name: Create GCE Firewall Rule for SSH
    local_action:
      module: gce_net
      name: "{{ resource_prefix }}-vpc"
      fwname: "{{ resource_prefix }}-ssh"
      allowed: tcp:22
      state: "present"
      src_range: "0.0.0.0/0"
      target_tags: "{{ resource_prefix }}-targets"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"
    when: groups['google_compute'] is defined
