---
#
# This playbook facilitates the creation of resources before creation of instances for a Zombie Chain cluster
#
# - VPC
# - Subnets
# - Internet Gateway
# - Route Table
# - EC2 Instance Profile
#
# The only value it looks for in the inventory is {{ resource_prefix }}
#
# ansible-playbook zombiechain-aws.yaml -vv -e resource_prefix=name-for-cluster
#

- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    vpc_name: "{{ resource_prefix }}"
    vpc_cidr: 10.10.0.0/16
    region: ap-southeast-1
    instance_profile: "{{ resource_prefix }}"
    availability_zones:
      - { ap-southeast-1a: 10.10.0.0/24 }
      - { ap-southeast-1b: 10.10.1.0/24 }
      - { ap-southeast-1c: 10.10.2.0/24 }
  tasks:

  - name: Create VPC
    ec2_vpc_net:
      name: "{{ vpc_name }}"
      cidr_block: "{{ vpc_cidr }}"
      region: "{{ region }}"
    register: vpc

  # - debug: var=vpc

  - name: Lookup route tables
    ec2_vpc_route_table_facts:
      region: "{{ region }}"
      filters:
        vpc-id: "{{ vpc.vpc.id }}"
    register: vpc_route_tables

  # - debug: var=vpc_route_tables

  - name: Create subnet
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{ vpc.vpc.id }}"
      cidr: "{{ item.value }}"
      az: "{{ item.key }}"
      tags:
        Name: "{{ vpc.vpc.tags.Name }}-{{ item.key }}"
    with_dict: "{{ availability_zones }}"
    register: subnets

  # - debug: var=subnets

  - name: Create internet gateway
    ec2_vpc_igw:
      vpc_id: "{{ vpc.vpc.id }}"
      state: present
      region: "{{ region }}"
      tags:
        Name: "{{ vpc.vpc.tags.Name }}-{{ region }}"
    register: igw

  # - debug: var=igw

  - set_fact:
      subnet_list: []

  - set_fact:
      subnet_list: "{{ subnet_list }} + ['{{ item.subnet.id }}']"
    with_items: "{{ subnets.results }}"

  - name: Set up public subnet route table
    ec2_vpc_route_table:
      vpc_id: "{{ vpc.vpc.id }}"
      region: "{{ region }}"
      subnets: "{{ subnet_list }}"
      lookup: id
      route_table_id: "{{ vpc_route_tables.route_tables[0].id }}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ igw.gateway_id }}"
      tags:
        Name: "{{ vpc.vpc.tags.Name }}-{{ region }}-rt"
    register: route_table

  - name: Create AWS instance profile
    iam_role:
      name: "{{ instance_profile }}"
      create_instance_profile: true
      assume_role_policy_document: "{{ lookup('file','zombiechain_policy.json') }}"
      description: "Instance profile for {{ resource_prefix }}"

  # - debug: var=route_table

  - name: Print information to be inserted into inventory
    debug:
      msg: "VPC id: {{ vpc.vpc.id }}, Subnets: {{ subnet_list }}, CIDR block: {{ vpc.vpc.cidr_block }}"

- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:

  tasks:
  - name: AWS key pair
    local_action:
      module: ec2_key
      name: "{{ resource_prefix }}_key-{{ item.key }}"
      region: "{{ item.key }}"
    with_dict: "{{ aws_regions }}"
    when: groups['amazon_ec2'] is defined
    register: aws_keypairs

  - name: Save key pairs locally
    local_action:
      module: copy
      content: "{{ item.key.private_key }}"
      dest: "~/.ssh/{{ resource_prefix }}_key-{{ item.item.key }}.pem"
      mode: 0600
    with_items: "{{ aws_keypairs.results }}"
    when: aws_keypairs.changed

  - name: AWS security groups in each region
    local_action:
      module: ec2_group
      name: "{{ resource_prefix }}_sg-{{ item.key }}"
      description: Security group for zombiechain instances
      vpc_id: "{{ item.value.vpc }}"
      region: "{{ item.key }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: icmp
          from_port: 8
          to_port:  -1
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 9100
          to_port: 9100
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          ports:
            - 46656-46658
            - 9999
          cidr_ip:
            - "{{ item.value.vpc_cidr }}"
            - "0.0.0.0/0"
    with_dict: "{{ aws_regions }}"
    when: groups['amazon_ec2'] is defined

  - name: Launch instances on AWS EC2
    local_action:
      module: ec2
      id: "{{ hostvars[item]['ansible_hostname'] }}"
      key_name: "{{ resource_prefix }}_key-{{ hostvars[item]['region'] }}"
      group: "{{ resource_prefix }}_sg-{{ hostvars[item]['region'] }}"
      instance_type: "{{ hostvars[item]['instance_type'] }}"
      image: "{{ aws_regions[hostvars[item]['region']]['ami'] }}"
      wait: yes
      wait_timeout: 500
      instance_profile_name: "{{ resource_prefix }}"
      instance_tags:
          Name: "{{ hostvars[item]['ansible_hostname'] }}"
      region: "{{ hostvars[item]['region'] }}"
      vpc_subnet_id: "{{ hostvars[item]['subnet'] }}"
      assign_public_ip: yes
      monitoring: yes
      user_data: "{{ hostvars[item]['user_data'] }}"
      volumes:
        - device_name: /dev/sda1
          volume_type: io1
          volume_size: "{{ disk_size }}"
          iops: 1000
          delete_on_termination: false
          name: "ssdisk-{{ hostvars[item]['ansible_hostname'] }}"
      state: present
    register: ec2_results
    with_items: "{{ groups['amazon_ec2'] }}"
    when: groups['amazon_ec2'] is defined

  - name: Initialize list to save IP addresses
    set_fact:
      ec2_public_ips: []

  # - debug:
  #     var: ec2_results.results

  - name: Collect AWS IP addresses
    set_fact:
      ec2_public_ips: "{{ ec2_public_ips }} + [ '{{ item.instances[0].public_ip }}/32' ]"
    with_items:
    - "{{ ec2_results.results }}"
    when: groups['amazon_ec2'] is defined

  - name: Append to AWS security groups
    local_action:
      module: ec2_group
      name: "{{ resource_prefix }}_sg-{{ item.key }}"
      description: Security group for zombiechain instances
      vpc_id: "{{ item.value.vpc }}"
      region: "{{ item.key }}"
      purge_rules: no
      rules:
        - proto: tcp
          ports:
            - 46656-46658
            - 9999
          cidr_ip: "{{ gce_public_ips }} + {{ ec2_public_ips }}"
    with_dict: "{{ aws_regions }}"
    when: groups['amazon_ec2'] is defined
