---
- name: Check if git installed
  become: yes
  package:
    name: "git"
    state: "present"

- name: Download prometheus
  become: yes
  git:
    repo: "https://github.com/vegasbrianc/prometheus.git"
    dest: "/root/prometheus/"
    force: yes
    depth: 1

- name: Generate docker-compose.yml
  become: yes
  template:
    src: "docker-compose.yml.j2"
    dest: "/root/prometheus/docker-compose.yml"

- name: Generate prometheus/prometheus.yml
  become: yes
  template:
    src: "prometheus/prometheus.yml.j2"
    dest: "/root/prometheus/prometheus/prometheus.yml"

- name: Start prometheus
  become: yes
  docker_service:
    project_src: "/root/prometheus/"
    pull: yes
    restarted: yes
