---

- name: Ensure dependencies are installed.
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "software-properties-common"

- name: Add Docker apt key.
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key

- name: Add Docker repository.
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install Docker.
  become: yes
  package:
    name: "docker-ce"
    state: "present"
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "started"
    enabled: "yes"

- name: Install pip
  become: yes
  package:
    name: "python3-pip"
    state: "present"

- name: Install docker-py
  become: yes
  pip:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "docker"
    - "docker-compose"
