---
- name: Copy loom binary
  become: yes
  copy:
    src: /tmp/loom-{{ loom_build }}
    dest: /usr/bin/loom
    owner: root
    group: root
    mode: 0755

- name: Check that the {{ working_directory }}/genesis.json exists
  stat:
    path: "{{ working_directory }}/genesis.json"
  register: stat_result_genesis

- name: Run loom init
  command: chdir={{ working_directory }} /usr/bin/loom init
  when: stat_result_genesis.stat.exists == False

- name: Copy loom.yml
  copy:
    src: files/loom.yml
    dest: "{{ working_directory }}/loom.yml"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644

# genesis.json #1

- name: Check that the {{ working_directory }}/genesis.json.original exists
  stat:
    path: "{{ working_directory }}/genesis.json.original"
  register: stat_result_genesis_original
  when: HOST_COUNT|int > 1

- name: Move original { working_directory }}/genesis.json to backup
  command: chdir={{ working_directory }} mv genesis.json genesis.json.original
  when: stat_result_genesis_original.stat.exists == False
  when: HOST_COUNT|int > 1

- slurp:
    path: "{{ working_directory }}/genesis.json.original"
  register: genesis_json_file
  when: HOST_COUNT|int > 1

- set_fact:
    genesis: "{{ (genesis_json_file.content|b64decode|from_json) }}"
  when: HOST_COUNT|int > 1

# genesis.json #2

- name: Check that the {{ working_directory }}/chaindata/config/genesis.json.original exists
  stat:
    path: "{{ working_directory }}/chaindata/config/genesis.json.original"
  register: stat_result_chaindata_genesis_original
  when: HOST_COUNT|int > 1

- name: Move original {{ working_directory }}/chaindata/config/genesis.json to backup
  command: chdir={{ working_directory }} mv chaindata/config/genesis.json chaindata/config/genesis.json.original
  when: stat_result_chaindata_genesis_original.stat.exists == False
  when: HOST_COUNT|int > 1

- slurp:
    path: "{{ working_directory }}/chaindata/config/genesis.json.original"
  register: genesis_chaindata_file
  when: HOST_COUNT|int > 1

- set_fact:
    genesis_chaindata: "{{ (genesis_chaindata_file.content|b64decode|from_json) }}"
  when: HOST_COUNT|int > 1

# nodekeys

- name: Get nodekey
  command: chdir={{ working_directory }} /usr/bin/loom nodekey
  register: nodekey
  when: HOST_COUNT|int > 1

- name: Keep nodekey
  set_fact:
    nodekey: "{{ nodekey.stdout_lines[0] }}"
  when: HOST_COUNT|int > 1

# Copy templates

- name: Copy newly combined {{ working_directory }}/chaindata/config/genesis.json
  template:
    src: templates/chaindata-config-genesis.json.j2
    dest: "{{ working_directory }}/chaindata/config/genesis.json"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  when: HOST_COUNT|int > 1

- name: Copy newly combined {{ working_directory }}/genesis.json
  template:
    src: templates/genesis.json.j2
    dest: "{{ working_directory }}/genesis.json"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  when: HOST_COUNT|int > 1

- name: Copy init script
  become: yes
  template:
    src: templates/loom.service.j2
    dest: /etc/systemd/system/loom.service
    owner: root
    group: root
    mode: 0644

# Restart

- name: Restart loom service
  become: yes
  systemd:
    state: restarted
    daemon_reload: yes
    name: loom.service
